### ISSUE TITLE
Malformed Unicode code sequence in the field

### ISSUE THREAD

**Issue by riazXrazor** [eddturtle/direct-upload#14]
```
<Error>
<Code>InvalidArgument</Code>
<Message>Malformed Unicode code sequence in the field.</Message>
<ArgumentName>formField</ArgumentName>
<RequestId>2B536FB1957426E6</RequestId>
<HostId>
U8FBvhiqGNYxJJSaMijXt225qf0gRFGzFyf/CwfS6vUkF/EBu8hQWGQEarZwO4xb/IPexOGdNxY=
</HostId>
</Error>
```

i am facing this problem, i ave no clue whats the error, can anybody plz help me out,
thanks in advance.

**Comment by eddturtle** [comment]
Hi, I've had a look at your Stackoverflow question (http://stackoverflow.com/q/42242832/402585) and I'm not sure what your issue is. Have you tried your code with a very basic upload file (with a simple name) along with a clean s3 bucket (just created/empty)? If it still doesn't work could you create an example file/project where it doesn't work (with only your aws credentials removed) and share it here to test with. Thanks

**Comment by riazXrazor** [comment]
Hi Edd, well thanks for the quick reply, we were banging our heads with what went wrong, as you said we set up a bare page with only form and upload to test out , it worked.
now we are figuring out whats wrong with our html, it looks exactly the same but dosn't seems to work, we are using the form with VusJS, may be thats the reason, i m not sure though.

**Comment by eddturtle** [comment]
Without a test case it's difficult to know, but does setting the form attribute `accept-charset="UTF-8"` make any difference? I wouldn't have thought VueJS makes any difference.
